// <auto-generated />
using System;
using FspScraper.Common.Models.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FspScraper.WebAPI.Migrations
{
    [DbContext(typeof(FspTimesContext))]
    partial class FspTimesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("FspScraper.Common.Models.FspTimes", b =>
                {
                    b.Property<string>("RegistrationNum")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AirTime");

                    b.Property<decimal?>("Engine1Total");

                    b.Property<decimal?>("Engine2Total");

                    b.Property<decimal?>("Hobbs");

                    b.Property<decimal?>("Prop1Total");

                    b.Property<decimal?>("Prop2Total");

                    b.HasKey("RegistrationNum");

                    b.ToTable("Times");
                });
#pragma warning restore 612, 618
        }
    }
}
